### ISSUE TITLE
All GitHub Actions workflows should `cat` the logs from failing tests.

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#2742]
`.github/workflows/scanbuild.yml` has:

```yaml
            - name: Test logs
              if: ${{ failure() }}
              run: |
                cat test-suite.log
                cat tests/*.log
```

better would be:

```yaml
            - name: Failed Test logs
              if: ${{ failure() }}
              run: |
                find build -name \*.trs | xargs grep -lw FAIL | sed -e 's/trs$/log/' | xargs cat
```

and every workflow should have this.
